version: '3.0'

services:
  app:
    restart: always
    container_name: concoder-app
    image: binimini/concoder-server:latest
    ports:
      - 8080:8080
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    deploy:
      resources:
        limits:
          memory: 200M
  mysql:
    restart: always
    container_name: concoder-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - concoder-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      MYSQL_DATABASE: ${SPRING_DATABASE_SCHEMA}
    deploy:
      resources:
        limits:
          memory: 300M

  redis:
    restart: always
    container_name: concoder-redis
    image: redis:6.0
    ports:
      - 6379:6379
    deploy:
      resources:
        limits:
          memory: 50M

volumes:
  concoder-volume:
